stages:
  - test-lint-build
  - publish
  - release

default:
  image: registry.mdcatapult.io/informatics/docker-images/ci/node
  tags:
    - wopr

test-lint-build:
  stage: test-lint-build
  image: registry.mdcatapult.io/informatics/docker-images/ci/node
  tags:
    - wopr
  artifacts:
    paths:
      - src/main.js
      - src/server.js
  before_script:
    - apt-get -yqq update && apt-get upgrade -yqq chromium libxss1 xvfb
    - export CHROME_BIN=/usr/bin/chromium
    - npm install
  script:
    - npm run lint
  coverage: /Lines\s+:\s(\d+\.?\d*)%\s\(\s\d+\/\d+\s\)/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - wopr
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release:
  stage: release
  script:
    - cictl exec release node
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish-master:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - wopr
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --destination $CI_REGISTRY_IMAGE
    - /kaniko/executor --context $CI_PROJECT_DIR --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
