stages:
  - test-lint-build
  - publish
  - release

test-lint-build:
  stage: test-lint-build
  image: registry.mdcatapult.io/informatics/docker-images/ci/node
  tags:
    - wopr
  artifacts:
    paths:
      - src/*
  before_script:
    - apt-get -yqq update && apt-get upgrade -yqq chromium libxss1 xvfb
    - export CHROME_BIN=/usr/bin/chromium
    - npm install
  script:
    - npm run lint
  coverage: /Lines\s+:\s(\d+\.?\d*)%\s\(\s\d+\/\d+\s\)/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish:
  stage: publish
  tags:
    - wopr
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --build-arg NEXUS_PASSWORD=$NEXUS_PASSWORD
      --build-arg CONSUMER_VERSION=$CI_COMMIT_REF_SLUG
      --build-arg CONSUMER_VERSION_HASH=$CI_COMMIT_SHORT_SHA
      --destination "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release:
  stage: release
  image: registry.mdcatapult.io/informatics/docker-images/ci/node
  tags:
    - wopr
  script:
    - /scripts/release.sh -b
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
